[2024-03-31T12:01:40.940+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: basic_etl_dag.extract_task manual__2024-03-31T12:01:37.820509+00:00 [queued]>
[2024-03-31T12:01:40.946+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: basic_etl_dag.extract_task manual__2024-03-31T12:01:37.820509+00:00 [queued]>
[2024-03-31T12:01:40.946+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2024-03-31T12:01:40.986+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): extract_task> on 2024-03-31 12:01:37.820509+00:00
[2024-03-31T12:01:40.990+0000] {standard_task_runner.py:57} INFO - Started process 13092 to run task
[2024-03-31T12:01:40.993+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'basic_etl_dag', 'extract_task', 'manual__2024-03-31T12:01:37.820509+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/basic_etl_dag.py', '--cfg-path', '/tmp/tmperm1im1z']
[2024-03-31T12:01:40.994+0000] {standard_task_runner.py:85} INFO - Job 12: Subtask extract_task
[2024-03-31T12:01:41.045+0000] {task_command.py:410} INFO - Running <TaskInstance: basic_etl_dag.extract_task manual__2024-03-31T12:01:37.820509+00:00 [running]> on host codespaces-e864db
[2024-03-31T12:01:41.137+0000] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='basic_etl_dag' AIRFLOW_CTX_TASK_ID='extract_task' AIRFLOW_CTX_EXECUTION_DATE='2024-03-31T12:01:37.820509+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-03-31T12:01:37.820509+00:00'
[2024-03-31T12:01:41.138+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-03-31T12:01:41.139+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'wget -c https://datahub.io/core/top-level-domain-names/r/top-level-domain-names.csv.csv -O /workspaces/hands-on-introduction-data-engineering-4395021/lab/end-to-end/basic-etl-extract-data.csv']
[2024-03-31T12:01:41.147+0000] {subprocess.py:86} INFO - Output:
[2024-03-31T12:01:41.234+0000] {subprocess.py:93} INFO - --2024-03-31 12:01:41--  https://datahub.io/core/top-level-domain-names/r/top-level-domain-names.csv.csv
[2024-03-31T12:01:41.244+0000] {subprocess.py:93} INFO - Resolving datahub.io (datahub.io)... 76.76.21.21
[2024-03-31T12:01:41.245+0000] {subprocess.py:93} INFO - Connecting to datahub.io (datahub.io)|76.76.21.21|:443... connected.
[2024-03-31T12:01:41.593+0000] {subprocess.py:93} INFO - HTTP request sent, awaiting response... 404 Not Found
[2024-03-31T12:01:41.593+0000] {subprocess.py:93} INFO - 2024-03-31 12:01:41 ERROR 404: Not Found.
[2024-03-31T12:01:41.594+0000] {subprocess.py:93} INFO - 
[2024-03-31T12:01:41.594+0000] {subprocess.py:97} INFO - Command exited with return code 8
[2024-03-31T12:01:41.616+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/python/3.10.13/lib/python3.10/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 8.
[2024-03-31T12:01:41.624+0000] {taskinstance.py:1345} INFO - Marking task as FAILED. dag_id=basic_etl_dag, task_id=extract_task, execution_date=20240331T120137, start_date=20240331T120140, end_date=20240331T120141
[2024-03-31T12:01:41.689+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 12 for task extract_task (Bash command failed. The command returned a non-zero exit code 8.; 13092)
[2024-03-31T12:01:41.727+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2024-03-31T12:01:41.747+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
