[2024-03-31T08:04:26.104+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: extract_dag.extract_task manual__2024-03-31T08:04:21.694218+00:00 [queued]>
[2024-03-31T08:04:26.109+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: extract_dag.extract_task manual__2024-03-31T08:04:21.694218+00:00 [queued]>
[2024-03-31T08:04:26.110+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2024-03-31T08:04:26.152+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): extract_task> on 2024-03-31 08:04:21.694218+00:00
[2024-03-31T08:04:26.155+0000] {standard_task_runner.py:57} INFO - Started process 8369 to run task
[2024-03-31T08:04:26.158+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'extract_dag', 'extract_task', 'manual__2024-03-31T08:04:21.694218+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/extract_dag.py', '--cfg-path', '/tmp/tmpzauy7d2j']
[2024-03-31T08:04:26.159+0000] {standard_task_runner.py:85} INFO - Job 6: Subtask extract_task
[2024-03-31T08:04:26.217+0000] {task_command.py:410} INFO - Running <TaskInstance: extract_dag.extract_task manual__2024-03-31T08:04:21.694218+00:00 [running]> on host codespaces-e864db
[2024-03-31T08:04:26.324+0000] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='extract_dag' AIRFLOW_CTX_TASK_ID='extract_task' AIRFLOW_CTX_EXECUTION_DATE='2024-03-31T08:04:21.694218+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-03-31T08:04:21.694218+00:00'
[2024-03-31T08:04:26.326+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-03-31T08:04:26.326+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'wget -c https://datahub.io/core/top-level-domain-names/r/top-level-domain-names.csv.csv -O /workspaces/hands-on-introduction-data-engineering-4395021/lab/orchestrated/airflow-extract-data.csv']
[2024-03-31T08:04:26.337+0000] {subprocess.py:86} INFO - Output:
[2024-03-31T08:04:26.343+0000] {subprocess.py:93} INFO - --2024-03-31 08:04:26--  https://datahub.io/core/top-level-domain-names/r/top-level-domain-names.csv.csv
[2024-03-31T08:04:26.348+0000] {subprocess.py:93} INFO - Resolving datahub.io (datahub.io)... 76.76.21.21
[2024-03-31T08:04:26.351+0000] {subprocess.py:93} INFO - Connecting to datahub.io (datahub.io)|76.76.21.21|:443... connected.
[2024-03-31T08:04:26.733+0000] {subprocess.py:93} INFO - HTTP request sent, awaiting response... 404 Not Found
[2024-03-31T08:04:26.738+0000] {subprocess.py:93} INFO - 2024-03-31 08:04:26 ERROR 404: Not Found.
[2024-03-31T08:04:26.738+0000] {subprocess.py:93} INFO - 
[2024-03-31T08:04:26.738+0000] {subprocess.py:97} INFO - Command exited with return code 8
[2024-03-31T08:04:26.746+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/python/3.10.13/lib/python3.10/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 8.
[2024-03-31T08:04:26.749+0000] {taskinstance.py:1345} INFO - Marking task as FAILED. dag_id=extract_dag, task_id=extract_task, execution_date=20240331T080421, start_date=20240331T080426, end_date=20240331T080426
[2024-03-31T08:04:26.793+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 6 for task extract_task (Bash command failed. The command returned a non-zero exit code 8.; 8369)
[2024-03-31T08:04:26.818+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2024-03-31T08:04:26.832+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
