[2024-03-31T08:04:07.813+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: extract_dag.extract_task manual__2024-03-31T08:04:04.010454+00:00 [queued]>
[2024-03-31T08:04:07.819+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: extract_dag.extract_task manual__2024-03-31T08:04:04.010454+00:00 [queued]>
[2024-03-31T08:04:07.819+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2024-03-31T08:04:07.858+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): extract_task> on 2024-03-31 08:04:04.010454+00:00
[2024-03-31T08:04:07.864+0000] {standard_task_runner.py:57} INFO - Started process 8048 to run task
[2024-03-31T08:04:07.868+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'extract_dag', 'extract_task', 'manual__2024-03-31T08:04:04.010454+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/extract_dag.py', '--cfg-path', '/tmp/tmpl4pw497i']
[2024-03-31T08:04:07.868+0000] {standard_task_runner.py:85} INFO - Job 5: Subtask extract_task
[2024-03-31T08:04:07.927+0000] {task_command.py:410} INFO - Running <TaskInstance: extract_dag.extract_task manual__2024-03-31T08:04:04.010454+00:00 [running]> on host codespaces-e864db
[2024-03-31T08:04:08.064+0000] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='extract_dag' AIRFLOW_CTX_TASK_ID='extract_task' AIRFLOW_CTX_EXECUTION_DATE='2024-03-31T08:04:04.010454+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-03-31T08:04:04.010454+00:00'
[2024-03-31T08:04:08.074+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-03-31T08:04:08.074+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'wget -c https://datahub.io/core/top-level-domain-names/r/top-level-domain-names.csv.csv -O /workspaces/hands-on-introduction-data-engineering-4395021/lab/orchestrated/airflow-extract-data.csv']
[2024-03-31T08:04:08.089+0000] {subprocess.py:86} INFO - Output:
[2024-03-31T08:04:08.161+0000] {subprocess.py:93} INFO - --2024-03-31 08:04:08--  https://datahub.io/core/top-level-domain-names/r/top-level-domain-names.csv.csv
[2024-03-31T08:04:08.178+0000] {subprocess.py:93} INFO - Resolving datahub.io (datahub.io)... 76.76.21.21
[2024-03-31T08:04:08.181+0000] {subprocess.py:93} INFO - Connecting to datahub.io (datahub.io)|76.76.21.21|:443... connected.
[2024-03-31T08:04:08.676+0000] {subprocess.py:93} INFO - HTTP request sent, awaiting response... 404 Not Found
[2024-03-31T08:04:08.752+0000] {subprocess.py:93} INFO - 2024-03-31 08:04:08 ERROR 404: Not Found.
[2024-03-31T08:04:08.752+0000] {subprocess.py:93} INFO - 
[2024-03-31T08:04:08.753+0000] {subprocess.py:97} INFO - Command exited with return code 8
[2024-03-31T08:04:08.761+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/python/3.10.13/lib/python3.10/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 8.
[2024-03-31T08:04:08.763+0000] {taskinstance.py:1345} INFO - Marking task as FAILED. dag_id=extract_dag, task_id=extract_task, execution_date=20240331T080404, start_date=20240331T080407, end_date=20240331T080408
[2024-03-31T08:04:08.804+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 5 for task extract_task (Bash command failed. The command returned a non-zero exit code 8.; 8048)
[2024-03-31T08:04:08.849+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2024-03-31T08:04:08.859+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
